package dev.hekuo.guard.core;

public enum CheckType {
    INVALID_PACKET, INVALID_ROTATION, MOVE_SPEED, MOVE_VERTICAL, TIMER, PHASE, FLIGHT, WATER_WALK,
    VEHICLE_PACKET, INTERACT_FLOOD, INVULNERABLE, REACH, THROUGH_WALL, ATTACK_FLOOD, MULTI_TARGET
}
